// Static fallback product data, used by products-loader.js only if Supabase is
// unreachable, so the public products page never renders blank. This mirrors
// supabase/seed_products.sql exactly (same source data, same order) — if you
// edit products through the dashboard, this file is not affected and does not
// need to be kept in sync for day-to-day edits, only if you rebuild the seed.
const PRODUCTS_FALLBACK_DATA = [
  { category: 'food', display_order: 0, image_url: './photo/الصمغ العربي.jpg', image_alt: 'Gum Arabic', title_en: 'Gum Arabic', title_ar: 'الصمغ العربي', description_en: "Sudan is the world's largest producer of gum arabic, prized for its purity and used in the food, pharmaceutical and cosmetic industries.", description_ar: 'يعتبر السودان أكبر منتج للصمغ العربي في العالم ويتميز بالنقاء والجودة العالية ويستخدم في الصناعات الغذائية والدوائية ومستحضرات التجميل.' },
  { category: 'food', display_order: 1, image_url: './photo/كركدية.jpg', image_alt: 'Hibiscus', title_en: 'Hibiscus (Karkade)', title_ar: 'الكركديه', description_en: 'A natural Sudanese product rich in antioxidants, used as a healthy beverage and natural source of vitamins.', description_ar: 'منتج سوداني طبيعي غني بمضادات الأكسدة ويستخدم كمشروب صحي ومصدر طبيعي للفيتامينات.' },
  { category: 'food', display_order: 2, image_url: './photo/بذور السمسم.jpg', image_alt: 'Sesame Seeds', title_en: 'Sesame Seeds', title_ar: 'السمسم', description_en: 'Among the finest sesame varieties in the world, used in food industries and the production of oils and tahini.', description_ar: 'من أجود أنواع السمسم عالميًا ويستخدم في الصناعات الغذائية وإنتاج الزيوت والطحينة.' },
  { category: 'food', display_order: 3, image_url: 'https://images.pexels.com/photos/8130681/pexels-photo-8130681.jpeg?auto=compress&cs=tinysrgb&w=800', image_alt: 'Tahini', title_en: 'Tahini', title_ar: 'الطحينة', description_en: 'A high-quality natural product made from the finest Sudanese sesame seeds.', description_ar: 'منتج طبيعي عالي الجودة مصنوع من أجود أنواع السمسم السوداني.' },
  { category: 'food', display_order: 4, image_url: './photo/زيت السمسم.jpg', image_alt: 'Sesame Oil', title_en: 'Sesame Oil', title_ar: 'زيت السمسم', description_en: 'A natural oil with a unique flavor and high nutritional value.', description_ar: 'زيت طبيعي يتميز بالنكهة الفريدة والقيمة الغذائية العالية.' },
  { category: 'food', display_order: 5, image_url: './photo/فول سوداني.jpg', image_alt: 'Peanuts', title_en: 'Peanuts', title_ar: 'الفول السوداني', description_en: 'A high-quality Sudanese agricultural product used across various food industries.', description_ar: 'منتج زراعي سوداني عالي الجودة يستخدم في الصناعات الغذائية المختلفة.' },
  { category: 'food', display_order: 6, image_url: 'https://images.pexels.com/photos/5149349/pexels-photo-5149349.jpeg?auto=compress&cs=tinysrgb&w=800', image_alt: 'Peanut Butter', title_en: 'Peanut Butter', title_ar: 'زبدة الفول السوداني', description_en: 'A food product rich in protein and energy, suitable for all ages.', description_ar: 'منتج غذائي غني بالبروتين والطاقة ومناسب لجميع الأعمار.' },
  { category: 'food', display_order: 7, image_url: 'https://images.pexels.com/photos/2348740/pexels-photo-2348740.jpeg?auto=compress&cs=tinysrgb&w=800', image_alt: 'Tamarind', title_en: 'Tamarind', title_ar: 'التمر الهندي', description_en: 'Used in the production of natural juices and beverages.', description_ar: 'يستخدم في صناعة العصائر والمشروبات الطبيعية.' },
  { category: 'food', display_order: 8, image_url: 'https://images.pexels.com/photos/36552911/pexels-photo-36552911.jpeg?auto=compress&cs=tinysrgb&w=800', image_alt: 'Waika (Dried Okra)', title_en: 'Waika (Dried Okra)', title_ar: 'الويكة', description_en: 'One of the most famous traditional Sudanese products, used in preparing popular dishes.', description_ar: 'من أشهر المنتجات السودانية التقليدية المستخدمة في إعداد الأطعمة الشعبية.' },
  { category: 'food', display_order: 9, image_url: 'https://images.pexels.com/photos/32281630/pexels-photo-32281630.jpeg?auto=compress&cs=tinysrgb&w=800', image_alt: 'Sudanese Spices', title_en: 'Sudanese Spices', title_ar: 'البهارات السودانية', description_en: 'Natural blends that add a distinctive flavor to dishes.', description_ar: 'خلطات طبيعية تضيف نكهة مميزة للأطعمة.' },
  { category: 'food', display_order: 10, image_url: 'https://images.pexels.com/photos/5634212/pexels-photo-5634212.jpeg?auto=compress&cs=tinysrgb&w=800', image_alt: 'Natural Honey', title_en: 'Natural Honey', title_ar: 'العسل الطبيعي', description_en: 'Pure Sudanese honey sourced from multiple natural origins.', description_ar: 'عسل سوداني نقي من مصادر طبيعية متعددة.' },
  { category: 'food', display_order: 11, image_url: 'https://images.pexels.com/photos/20632754/pexels-photo-20632754.jpeg?auto=compress&cs=tinysrgb&w=800', image_alt: 'Dates', title_en: 'Dates', title_ar: 'التمور', description_en: 'High-quality dates with a rich nutritional value.', description_ar: 'تمور عالية الجودة ذات قيمة غذائية مرتفعة.' },

  { category: 'agri', display_order: 12, image_url: 'https://images.pexels.com/photos/28906328/pexels-photo-28906328.jpeg?auto=compress&cs=tinysrgb&w=800', image_alt: 'Sorghum', title_en: 'Sorghum', title_ar: 'الذرة', description_en: 'A strategic crop used in food production and various industries.', description_ar: 'محصول استراتيجي يستخدم في الغذاء والصناعات المختلفة.' },
  { category: 'agri', display_order: 13, image_url: 'https://images.pexels.com/photos/16977456/pexels-photo-16977456.jpeg?auto=compress&cs=tinysrgb&w=800', image_alt: 'Millet', title_en: 'Millet', title_ar: 'الدخن', description_en: 'One of the important food crops with a high nutritional value.', description_ar: 'من المحاصيل الغذائية المهمة ذات القيمة الغذائية العالية.' },
  { category: 'agri', display_order: 14, image_url: 'https://images.pexels.com/photos/4264828/pexels-photo-4264828.jpeg?auto=compress&cs=tinysrgb&w=800', image_alt: 'Sudanese Cotton', title_en: 'Sudanese Cotton', title_ar: 'القطن السوداني', description_en: 'Known for its long fiber and world-class quality.', description_ar: 'يتميز بطول الألياف والجودة العالمية.' },
  { category: 'agri', display_order: 15, image_url: 'https://images.pexels.com/photos/37816783/pexels-photo-37816783.jpeg?auto=compress&cs=tinysrgb&w=800', image_alt: 'Mango', title_en: 'Mango', title_ar: 'المانجو', description_en: 'A Sudanese fruit with a distinctive taste and superior quality.', description_ar: 'فاكهة سودانية ذات مذاق مميز وجودة عالية.' },
  { category: 'agri', display_order: 16, image_url: 'https://images.pexels.com/photos/4399936/pexels-photo-4399936.jpeg?auto=compress&cs=tinysrgb&w=800', image_alt: 'Banana', title_en: 'Banana', title_ar: 'الموز', description_en: 'An agricultural product in strong demand across local and export markets.', description_ar: 'منتج زراعي مطلوب في الأسواق المحلية والخارجية.' },
  { category: 'agri', display_order: 17, image_url: 'https://images.pexels.com/photos/5782205/pexels-photo-5782205.jpeg?auto=compress&cs=tinysrgb&w=800', image_alt: 'Guava', title_en: 'Guava', title_ar: 'الجوافة', description_en: 'A fruit rich in vitamins and nutrients.', description_ar: 'فاكهة غنية بالفيتامينات والعناصر الغذائية.' },
  { category: 'agri', display_order: 18, image_url: 'https://images.pexels.com/photos/13200742/pexels-photo-13200742.jpeg?auto=compress&cs=tinysrgb&w=800', image_alt: 'Sunflower', title_en: 'Sunflower', title_ar: 'عباد الشمس', description_en: 'Used in the production of natural vegetable oils.', description_ar: 'يستخدم في إنتاج الزيوت النباتية.' },

  { category: 'live', display_order: 19, image_url: './photo/ابقار.jpg', image_alt: 'Cattle', title_en: 'Cattle', title_ar: 'الأبقار', description_en: 'Sudanese breeds known for their quality and high productivity.', description_ar: 'سلالات سودانية معروفة بجودتها وإنتاجيتها العالية.' },
  { category: 'live', display_order: 20, image_url: './photo/اغنام ومعاز.jpg', image_alt: 'Sheep & Goats', title_en: 'Sheep & Goats', title_ar: 'الأغنام والماعز', description_en: 'Among the finest sheep and goat breeds dedicated for export.', description_ar: 'من أفضل أنواع الأغنام المخصصة للتصدير.' },
  { category: 'live', display_order: 21, image_url: './photo/جمال.jpg', image_alt: 'Camels', title_en: 'Camels', title_ar: 'الإبل', description_en: 'Distinguished by their adaptability and high quality.', description_ar: 'تتميز بالقدرة على التكيف والجودة العالية.' },
  { category: 'live', display_order: 22, image_url: 'https://images.pexels.com/photos/33157191/pexels-photo-33157191.jpeg?auto=compress&cs=tinysrgb&w=800', image_alt: 'Meat', title_en: 'Meat', title_ar: 'اللحوم', description_en: 'Fresh and frozen meat processed according to international standards.', description_ar: 'لحوم طازجة ومجمدة وفق المعايير الدولية.' },
  { category: 'live', display_order: 23, image_url: 'https://images.pexels.com/photos/248412/pexels-photo-248412.jpeg?auto=compress&cs=tinysrgb&w=800', image_alt: 'Dairy & Derivatives', title_en: 'Dairy & Derivatives', title_ar: 'الألبان ومشتقاتها', description_en: 'Natural products of high quality.', description_ar: 'منتجات طبيعية عالية الجودة.' },
  { category: 'live', display_order: 24, image_url: 'https://images.pexels.com/photos/30902515/pexels-photo-30902515.jpeg?auto=compress&cs=tinysrgb&w=800', image_alt: 'Hides & Leather', title_en: 'Hides & Leather', title_ar: 'الجلود', description_en: 'Natural hides used across various leather industries.', description_ar: 'جلود طبيعية تستخدم في الصناعات الجلدية المختلفة.' },

  { category: 'gold', display_order: 25, image_url: './photo/الذهب.jpg', image_alt: 'Raw Gold', title_en: 'Raw Gold', title_ar: 'الذهب الخام', description_en: "Sudan is one of Africa's largest gold-producing countries, and Sudanese gold is known for its exceptional quality.", description_ar: 'يعد السودان من أكبر الدول المنتجة للذهب في أفريقيا ويتميز الذهب السوداني بجودته العالية.' },
  { category: 'gold', display_order: 26, image_url: 'https://images.pexels.com/photos/346547/pexels-photo-346547.jpeg?auto=compress&cs=tinysrgb&w=800', image_alt: 'Gold Bars', title_en: 'Gold Bars', title_ar: 'السبائك الذهبية', description_en: 'Gold bars compliant with international specifications.', description_ar: 'سبائك ذهبية مطابقة للمواصفات العالمية.' },
  { category: 'gold', display_order: 27, image_url: 'https://images.pexels.com/photos/4735888/pexels-photo-4735888.jpeg?auto=compress&cs=tinysrgb&w=800', image_alt: 'Gold Jewelry', title_en: 'Gold Jewelry', title_ar: 'المشغولات الذهبية', description_en: 'Luxurious gold jewelry and ornaments.', description_ar: 'حلي ومجوهرات ذهبية فاخرة.' },

  { category: 'indu', display_order: 28, image_url: './photo/منتجات النسيج.jpg', image_alt: 'Textiles & Clothing', title_en: 'Textiles & Clothing', title_ar: 'المنسوجات والملابس', description_en: 'A diverse range of high-quality cotton products.', description_ar: 'منتجات قطنية متنوعة ذات جودة عالية.' },
  { category: 'indu', display_order: 29, image_url: 'https://images.pexels.com/photos/11591259/pexels-photo-11591259.jpeg?auto=compress&cs=tinysrgb&w=800', image_alt: 'Furniture', title_en: 'Furniture', title_ar: 'الأثاث', description_en: 'Wooden furniture distinguished by durability and beautiful design.', description_ar: 'أثاث خشبي يتميز بالمتانة والتصميم الجميل.' },
  { category: 'indu', display_order: 30, image_url: 'https://images.pexels.com/photos/5217900/pexels-photo-5217900.jpeg?auto=compress&cs=tinysrgb&w=800', image_alt: 'Cleaning Products', title_en: 'Cleaning Products', title_ar: 'المنظفات', description_en: 'A variety of cleaning products for household and commercial use.', description_ar: 'منتجات تنظيف متنوعة للاستخدام المنزلي والتجاري.' },
  { category: 'indu', display_order: 31, image_url: 'https://images.pexels.com/photos/7795760/pexels-photo-7795760.jpeg?auto=compress&cs=tinysrgb&w=800', image_alt: 'Natural Cosmetics', title_en: 'Natural Cosmetics', title_ar: 'مستحضرات التجميل الطبيعية', description_en: 'Products based on natural Sudanese ingredients.', description_ar: 'منتجات تعتمد على مكونات طبيعية سودانية.' },
  { category: 'indu', display_order: 32, image_url: 'https://images.pexels.com/photos/5025503/pexels-photo-5025503.jpeg?auto=compress&cs=tinysrgb&w=800', image_alt: 'Packaging', title_en: 'Packaging', title_ar: 'التعبئة والتغليف', description_en: 'Modern packaging solutions serving commercial and industrial sectors.', description_ar: 'حلول حديثة لخدمة القطاعات التجارية والصناعية.' },

  { category: 'craft', display_order: 33, image_url: 'https://images.pexels.com/photos/34667136/pexels-photo-34667136.jpeg?auto=compress&cs=tinysrgb&w=800', image_alt: 'Handmade Baskets', title_en: 'Handmade Baskets', title_ar: 'السلال اليدوية', description_en: 'Products made from natural materials in distinctive heritage designs.', description_ar: 'منتجات مصنوعة من خامات طبيعية بأشكال تراثية مميزة.' },
  { category: 'craft', display_order: 34, image_url: 'https://images.pexels.com/photos/15440777/pexels-photo-15440777.jpeg?auto=compress&cs=tinysrgb&w=800', image_alt: 'Pottery', title_en: 'Pottery', title_ar: 'الفخار', description_en: 'Artistic and handcrafted works reflecting Sudanese heritage.', description_ar: 'أعمال فنية وحرفية تعكس التراث السوداني.' },
  { category: 'craft', display_order: 35, image_url: 'https://images.pexels.com/photos/31661556/pexels-photo-31661556.jpeg?auto=compress&cs=tinysrgb&w=800', image_alt: 'Leather Crafts', title_en: 'Leather Crafts', title_ar: 'المشغولات الجلدية', description_en: 'High-quality handmade bags, belts and leather goods.', description_ar: 'حقائب وأحزمة ومنتجات جلدية عالية الجودة.' },
  { category: 'craft', display_order: 36, image_url: 'https://images.pexels.com/photos/18363710/pexels-photo-18363710.jpeg?auto=compress&cs=tinysrgb&w=800', image_alt: 'Heritage Antiques & Gifts', title_en: 'Heritage Antiques & Gifts', title_ar: 'التحف والهدايا التراثية', description_en: 'Artistic pieces representing authentic Sudanese culture.', description_ar: 'قطع فنية تمثل الثقافة السودانية الأصيلة.' },
];

// Fallback-only: used by products-loader.js when Supabase is unreachable.
// Categories added later from the dashboard live in the `categories` table
// and won't appear here — that's fine, this is just the emergency safety net.
const PRODUCT_CATEGORY_LABELS = {
  en: { food: 'Food Products', agri: 'Agricultural', live: 'Livestock', gold: 'Sudanese Gold', indu: 'Industries', craft: 'Handicrafts' },
  ar: { food: 'المنتجات الغذائية', agri: 'زراعي', live: 'مواشي', gold: 'الذهب السوداني', indu: 'صناعات', craft: 'حرف يدوية' },
};

const PRODUCT_CATEGORIES = ['food', 'agri', 'live', 'gold', 'indu', 'craft'];
