// Static fallback for projects.html, used by projects-loader.js when Supabase
// is unreachable. Mirrors the rows in supabase/seed_projects_gallery.sql —
// keep in sync if the seed changes.
const PROJECTS_FALLBACK_DATA = [
  { title_en: 'OSLI Smart City', title_ar: 'مدينة OSLI الذكية', category_en: 'Urban Development', category_ar: 'التطوير العمراني', location_en: 'Under Construction', location_ar: 'مشروع تحت الإنشاء', image_url: './photo/الخريطة.png', image_alt: 'OSLI Smart City', display_order: 0 },
  { title_en: 'Sesame Export to China', title_ar: 'تصدير السمسم إلى الصين', category_en: 'Agricultural Export', category_ar: 'تصدير زراعي', location_en: 'Sudan → China', location_ar: 'السودان ← الصين', image_url: 'https://images.pexels.com/photos/2255935/pexels-photo-2255935.jpeg?auto=compress&cs=tinysrgb&w=800', image_alt: 'Sesame Export', display_order: 1 },
  { title_en: 'Port Sudan Logistics Hub', title_ar: 'مركز بورتسودان اللوجستي', category_en: 'Logistics', category_ar: 'الخدمات اللوجستية', location_en: 'Port Sudan, Sudan', location_ar: 'بورتسودان، السودان', image_url: 'https://images.pexels.com/photos/1117210/pexels-photo-1117210.jpeg?auto=compress&cs=tinysrgb&w=800', image_alt: 'Logistics Hub', display_order: 2 },
  { title_en: 'ERP System Implementation', title_ar: 'تنفيذ نظام ERP', category_en: 'Technology', category_ar: 'التقنية', location_en: 'Riyadh, Saudi Arabia', location_ar: 'الرياض، السعودية', image_url: 'https://images.pexels.com/photos/7988079/pexels-photo-7988079.jpeg?auto=compress&cs=tinysrgb&w=800', image_alt: 'ERP Implementation', display_order: 3 },
  { title_en: 'Gold Mining Partnership', title_ar: 'شراكة تعدين الذهب', category_en: 'Mining', category_ar: 'التعدين', location_en: 'Red Sea Hills, Sudan', location_ar: 'جبال البحر الأحمر، السودان', image_url: 'https://images.pexels.com/photos/1078884/pexels-photo-1078884.jpeg?auto=compress&cs=tinysrgb&w=800', image_alt: 'Mining Project', display_order: 4 },
  { title_en: 'Riyadh Investment Tower', title_ar: 'برج الرياض الاستثماري', category_en: 'Investment', category_ar: 'الاستثمار', location_en: 'Riyadh, Saudi Arabia', location_ar: 'الرياض، السعودية', image_url: 'https://images.pexels.com/photos/1105766/pexels-photo-1105766.jpeg?auto=compress&cs=tinysrgb&w=800', image_alt: 'Investment Tower', display_order: 5 },
  { title_en: 'Livestock Export to UAE', title_ar: 'تصدير المواشي إلى الإمارات', category_en: 'Livestock', category_ar: 'المواشي', location_en: 'Sudan → UAE', location_ar: 'السودان ← الإمارات', image_url: 'https://images.pexels.com/photos/422218/pexels-photo-422218.jpeg?auto=compress&cs=tinysrgb&w=800', image_alt: 'Livestock Export', display_order: 6 },
  { title_en: 'Construction Materials Supply', title_ar: 'توريد مواد البناء', category_en: 'Industrial', category_ar: 'الصناعة', location_en: 'Khartoum, Sudan', location_ar: 'الخرطوم، السودان', image_url: 'https://images.pexels.com/photos/1797428/pexels-photo-1797428.jpeg?auto=compress&cs=tinysrgb&w=800', image_alt: 'Construction', display_order: 7 },
  { title_en: 'Cloud Migration Project', title_ar: 'مشروع الترحيل السحابي', category_en: 'Technology', category_ar: 'التقنية', location_en: 'Dubai, UAE', location_ar: 'دبي، الإمارات', image_url: 'https://images.pexels.com/photos/3184398/pexels-photo-3184398.jpeg?auto=compress&cs=tinysrgb&w=800', image_alt: 'Tech Partnership', display_order: 8 },
  { title_en: 'Sesame Oil Processing Plant', title_ar: 'مصنع معالجة زيت السمسم', category_en: 'Natural Oils', category_ar: 'الزيوت الطبيعية', location_en: 'Gedaref, Sudan', location_ar: 'القضارف، السودان', image_url: 'https://images.pexels.com/photos/2749165/pexels-photo-2749165.jpeg?auto=compress&cs=tinysrgb&w=800', image_alt: 'Oil Processing', display_order: 9 },
];
