// ============================================================
// NASHVELL INTERNATIONAL - DYNAMIC TRANSLATION SYSTEM
// ============================================================

const translations = {
  en: {
    // ── Navbar ──
    nav_home: "Home",
    nav_about: "About Us",
    nav_products: "Products",
    nav_projects: "Projects",
    nav_investment: "Investment",
    nav_technology: "Technology",
    nav_logistics: "Logistics",
    nav_media: "Media Center",
    nav_gallery: "Gallery",
    nav_contact: "Contact Us",
    brand_tagline: "International Trading Co. Ltd.",
    lang_btn_text: "العربية",

    // ── Shared buttons ──
    btn_read_more: "Read More",
    btn_learn_more: "Learn More",

    // ── Hero Section (Home) ──
    hero_badge: "Premium Corporate Solutions",
    hero_title: "Pioneers in Trade and Innovative Investments",
    hero_subtitle: "Your Strategic Partner for Global Success",
    hero_desc: "We provide integrated solutions in international trade, logistics, and strategic investments, leveraging the latest technologies to achieve growth and excellence for our partners.",
    hero_btn_main: "Discover Our Services",
    hero_btn_outline: "Contact Us",
    hero_right_title: "Our Core Technologies",
    hero_right_sub: "Driving innovation in every sector.",
    hero_right_btn: "Explore Technology",
    tech_icon_supply: "Supply Chain",
    tech_icon_data: "Data Analysis",
    tech_icon_automation: "Automation",
    tech_icon_security: "Cybersecurity",
    tech_icon_cloud: "Cloud Services",
    tech_icon_iot: "IoT",
    stat_experience: "Years of Experience",
    stat_projects: "Completed Projects",
    stat_clients: "Satisfied Clients",
    stat_countries: "Countries Worldwide",
    stat_products: "Sudanese Products",

    // ── Section Titles ──
    section_title_about: "About Nashvell",
    section_subtitle_about: "A legacy of trust and a future of innovation.",
    section_title_products: "Our Products",
    section_subtitle_products: "A diverse portfolio of high-quality products meeting global standards.",
    section_title_services: "Our Core Services",
    section_subtitle_services: "Integrated services designed for efficiency and growth.",
    section_title_tech_tag: "Our Technology",
    section_title_tech: "Technology & Innovation",
    section_subtitle_tech_full: "Integrated technology solutions crafted to drive digital transformation for businesses across the region.",
    section_subtitle_tech: "Harnessing technology to redefine industry standards.",
    section_title_investment: "Investment Opportunities",
    section_subtitle_investment: "Strategic investment opportunities in promising sectors.",
    section_title_logistics: "Advanced Logistics",
    section_subtitle_logistics: "Smart and efficient logistics solutions for your business.",
    section_title_partners: "Our Partners",
    section_subtitle_partners: "We are proud to collaborate with leading global brands.",
    section_title_certs: "Certificates & Accreditations",
    section_subtitle_certs: "Committed to the highest standards of quality and excellence.",
    section_title_gallery: "Our Gallery",
    section_subtitle_gallery: "A glimpse into our world of operations and achievements.",
    section_title_video: "Building The Future, Together",
    section_subtitle_video: "Watch our journey and discover the values that drive us forward.",
    section_title_contact: "Get In Touch",
    section_subtitle_contact: "We are here to help. Contact us for any inquiries.",

    // ── Home: Products ──
    product_cat_export: "Export",
    product_title_agri: "Agricultural Products",
    product_desc_agri: "Sesame, Peanuts, Hibiscus & more",
    product_cat_premium: "Premium",
    product_title_oils: "Natural Oils",
    product_desc_oils: "Sesame Oil, Gum Arabic, Shea Butter",
    product_cat_live: "Live Export",
    product_title_livestock: "Livestock",
    product_desc_livestock: "Cattle, Sheep, Camels & Goats",
    product_cat_mining: "Mining",
    product_title_mining: "Mining & Minerals",
    product_desc_mining: "Gold, Chromite, Copper",
    product_cat_industrial: "Industrial",
    product_title_industrial: "Industrial Products",
    product_desc_industrial: "Construction Materials, Equipment",
    product_btn_explore: "Explore",

    // ── Home: Services ──
    service_title_logistics: "Logistics Services",
    service_item_road: "Road Freight",
    service_item_air: "Air Freight",
    service_item_customs: "Customs Clearance",
    service_item_warehousing: "Warehousing & Distribution",
    service_item_tracking: "Shipment Tracking",
    service_btn_learn: "Learn More",
    service_title_investment: "Investment & Projects",
    service_item_opportunities: "Investment Opportunities",
    service_item_partnerships: "Strategic Partnerships",
    service_item_feasibility: "Feasibility Studies",
    service_item_management: "Project Management",
    service_title_global: "Global Partnerships",
    service_desc_global: "We work with partners around the world to build a better, more sustainable future through strong strategic trade relationships.",

    // ── Home: Technology cards ──
    tech_btn_all: "View All Services",
    tech_card_title_erp: "ERP Systems",
    tech_card_desc_erp: "Enterprise resource planning tailored to your business needs.",
    tech_card_title_web: "Web Development",
    tech_card_desc_web: "Modern, responsive websites and web applications.",
    tech_card_title_mobile: "Mobile Apps",
    tech_card_desc_mobile: "iOS and Android applications for global audiences.",
    tech_card_title_ai: "Artificial Intelligence",
    tech_card_desc_ai: "AI-powered solutions for automation and analytics.",
    tech_card_title_security: "Cyber Security",
    tech_card_desc_security: "Advanced security systems to protect your digital assets.",
    tech_card_title_cloud: "Cloud Solutions",
    tech_card_desc_cloud: "Scalable cloud infrastructure and migration services.",

    // ── Home: Preview panels ──
    preview_title_gallery: "Photo Gallery",
    preview_title_video: "Video Gallery",
    preview_title_partners: "Our Clients & Partners",
    preview_title_certs: "Our Certificates",
    preview_title_contact: "Contact Us",
    preview_btn_view_all: "View All",

    // ── Home: Values bar ──
    value_quality: "High Quality According to Global Standards",
    value_pricing: "Competitive Pricing",
    value_delivery: "On-Time Delivery",
    value_support: "Continuous Technical Support",
    value_innovation: "Innovative Solutions",

    // ── Contact Form ──
    contact_label_name: "Full Name",
    contact_placeholder_name: "Enter your full name",
    contact_label_email: "Email Address",
    contact_placeholder_email: "Enter your email address",
    contact_label_service: "Service of Interest",
    contact_option_default: "Select a service",
    contact_option_trade: "International Trade",
    contact_option_logistics: "Logistics",
    contact_option_investment: "Investment",
    contact_label_message: "Message",
    contact_placeholder_message: "Write your message here...",
    contact_btn_submit: "Send Message",

    // ── Footer ──
    footer_desc: "Nashvell International Trading Co. Ltd. is a leader in providing comprehensive solutions in trade, logistics, and investment.",
    footer_title_links: "Quick Links",
    footer_title_newsletter: "Newsletter",
    footer_newsletter_desc: "Subscribe to our newsletter to get the latest updates.",
    footer_placeholder_newsletter: "Your Email Address",
    footer_btn_newsletter: "Subscribe",
    footer_design: "Designed with precision — Excellence in Every Detail",
    footer_copyright: "© 2024 Nashvell International. All Rights Reserved.",

    // ============================================================
    // ABOUT PAGE
    // ============================================================
    about_hero_tag: "Get to know us",
    about_hero_title: "About Nashvell",
    about_hero_subtitle: "Three decades of excellence in international trade, technology and investment.",
    about_badge_num: "30+",
    about_badge_label: "Years of Excellence",
    about_intro_tag: "Our Story",
    about_intro_title: "A Legacy of International Trade",
    about_intro_p1: "Founded in 1994, Nashvell International Trading Co. Ltd. has grown from a regional trading house into a diversified international enterprise. Headquartered in Saudi Arabia with deep roots in Sudan, we connect African products with global markets.",
    about_intro_p2: "Our operations span agricultural exports, natural oils, livestock, mining, industrial products, technology solutions, logistics and strategic investments — all driven by a commitment to quality, integrity and long-term partnerships.",
    about_feature1: "Global trade network across 25+ countries",
    about_feature2: "Premium Sudanese products exported worldwide",
    about_feature3: "Integrated technology and logistics solutions",
    about_feature4: "ISO-certified quality management systems",
    about_btn_contact: "Get in Touch",
    about_vission_tag: "What Drives Us",
    about_vission_title: "Vision, Mission & Values",
    about_vision_card_title: "Our Vision",
    about_vision_card_desc: "To be the leading bridge connecting Sudanese products and African resources with global markets, setting the standard for excellence in international trade.",
    about_mission_card_title: "Our Mission",
    about_mission_card_desc: "To deliver premium products, innovative technology solutions and reliable logistics services that create lasting value for our clients, partners and communities.",
    about_values_card_title: "Our Values",
    about_values_card_desc: "Integrity, quality, innovation and partnership are the foundations of everything we do — guiding our relationships with clients, suppliers and communities.",
    about_team_tag: "Our Leadership",
    about_team_title: "Meet the Team",
    about_team_subtitle: "Experienced leaders guiding our vision for global trade and innovation.",
    about_team_member1_name: "Dr. Salah",
    about_team_member1_role: "Owner of the Company",
    about_team_member2_name: "Khalid Mahmoud",
    about_team_member2_role: "Operating Officer",
    about_team_member3_name: "Sarah Ibrahim",
    about_team_member3_role: "Technology Officer",
    about_team_member4_name: "Omar Hassan",
    about_team_member4_role: "Financial Officer",
    about_certs_tag: "Quality & Trust",
    about_certs_title: "Our Certifications",
    about_cert1_title: "ISO 9001:2015",
    about_cert1_desc: "Quality Management System Certified",
    about_cert2_title: "ISO 14001:2015",
    about_cert2_desc: "Environmental Management Certified",
    about_cert3_title: "ISO 45001:2018",
    about_cert3_desc: "Occupational Health & Safety",
    about_cert4_title: "Best Exporter 2023",
    about_cert4_desc: "Sudan Export Excellence Award",

    // ============================================================
    // CONTACT PAGE
    // ============================================================
    contact_hero_tag: "Get In Touch",
    contact_hero_title: "Contact Us",
    contact_hero_subtitle: "We'd love to hear from you. Reach out for partnerships, inquiries or support.",
    contact_info_tag: "Contact Information",
    contact_info_title: "Let's Talk",
    contact_info_desc: "Reach out to us through any of the following channels. Our team is ready to assist you.",
    contact_office_label: "Head Office",
    contact_office_ksa: "Kingdom of Saudi Arabia",
    contact_phone_ksa_label: "Phone (KSA)",
    contact_phone_ksa: "+966 50 441 5254",
    contact_phone_sd_label: "Phone (Sudan)",
    contact_phone_sd: "+249 90 717 5005",
    contact_email_label: "Email",
    contact_email_main: "qqsalah@hotmail.com",
    contact_website_label: "Website",
    contact_website_url: "www.nashvell.com",
    contact_form_tag: "Send a Message",
    contact_form_title: "Contact Form",
    contact_form_desc: "Fill out the form below and our team will get back to you within 24 hours.",
    contact_label_phone: "Phone Number",
    contact_placeholder_phone: "+966 5X XXX XXXX",
    contact_label_subject: "Subject",
    contact_option_default_subject: "Select a subject",
    contact_option_inquiry: "General Inquiry",
    contact_option_tech: "Technology Services",
    contact_option_media: "Media & Press",
    contact_offices_tag: "Our Locations",
    contact_offices_title: "Global Offices",
    contact_office1_title: "Riyadh, Saudi Arabia",
    contact_office1_desc: "Head Office\nKing Fahd District, Riyadh, KSA\n+966 50 441 5254",
    contact_office2_title: "Khartoum, Sudan",
    contact_office2_desc: "Regional Office\nAl-Mogran, Khartoum, Sudan\n+249 90 717 5005",
    contact_office3_title: "Port Sudan, Sudan",
    contact_office3_desc: "Logistics Hub\nPort Sudan Harbor, Sudan\n+249 90 717 5005",

    // ============================================================
    // GALLERY PAGE
    // ============================================================
    gallery_hero_tag: "Visual Journey",
    gallery_hero_title: "Our Gallery",
    gallery_hero_subtitle: "A visual showcase of our products, projects, operations and corporate events.",
    gallery_section_tag: "Moments Captured",
    gallery_section_title: "Photo Gallery",
    gallery_section_subtitle: "Click any image to view in full size.",

    // ============================================================
    // PRODUCTS PAGE
    // ============================================================
    prod_hero_tag: "What We Offer",
    prod_hero_title: "Our Products",
    prod_hero_sub: "Premium Sudanese products exported to over 25 countries worldwide.",
    prod_catalog_tag: "Our Catalog",
    prod_catalog_title: "Explore Our Products",
    prod_catalog_sub: "From Sudan's fertile lands to the world's markets — quality you can trust.",
    prod_filter_all: "All Products",
    prod_filter_agri: "Agricultural",
    prod_filter_oils: "Natural Oils",
    prod_filter_live: "Livestock",
    prod_filter_mine: "Mining",
    prod_filter_indu: "Industrial",
    prod_cat_agri: "Agricultural",
    prod_cat_oils: "Natural Oils",
    prod_cat_live: "Livestock",
    prod_cat_mine: "Mining",
    prod_cat_indu: "Industrial",
    prod_item1_title: "Sesame Seeds",
    prod_item1_desc: "Premium white and golden sesame seeds sourced from Sudan's fertile regions, rich in oil content and flavor.",
    prod_item2_title: "Hibiscus (Karkade)",
    prod_item2_desc: "High-quality dried hibiscus flowers, known for vibrant color and health benefits, exported globally.",
    prod_item3_title: "Peanuts",
    prod_item3_desc: "Carefully selected peanuts from Sudan's agricultural heartlands, meeting international quality standards.",
    prod_item4_title: "Sesame Oil",
    prod_item4_desc: "Cold-pressed premium sesame oil, rich in nutrients and ideal for culinary and cosmetic applications.",
    prod_item5_title: "Gum Arabic",
    prod_item5_desc: "Premium grade gum arabic (hashab and talha), Sudan's finest natural export used in industries worldwide.",
    prod_item6_title: "Shea Butter",
    prod_item6_desc: "Unrefined organic shea butter, prized in cosmetics and skincare for its nourishing properties.",
    prod_item7_title: "Cattle Export",
    prod_item7_desc: "Healthy, well-nourished cattle raised on Sudan's natural pastures, meeting halal and export standards.",
    prod_item8_title: "Sheep & Goats",
    prod_item8_desc: "High-quality sheep and goats for export, raised in optimal conditions with veterinary certification.",
    prod_item9_title: "Camels",
    prod_item9_desc: "Premium camels for export to Gulf and international markets, known for strength and quality.",
    prod_item10_title: "Gold",
    prod_item10_desc: "Ethically-sourced gold from Sudan's rich mining regions, refined and certified for international trade.",
    prod_item11_title: "Chromite",
    prod_item11_desc: "High-grade chromite ore for industrial applications, meeting strict metallurgical specifications.",
    prod_item12_title: "Copper Ore",
    prod_item12_desc: "Premium copper ore extracted from Sudan's mineral-rich deposits, ready for industrial processing.",
    prod_item13_title: "Construction Materials",
    prod_item13_desc: "High-quality cement, aggregates and construction materials for regional infrastructure projects.",
    prod_item14_title: "Industrial Equipment",
    prod_item14_desc: "Heavy machinery and industrial equipment supplied to sectors across construction and manufacturing.",
    prod_item15_title: "Textile Products",
    prod_item15_desc: "Cotton and textile products manufactured to international standards for global fashion and industry.",
    prod_cta_title: "Interested in Our Products?",
    prod_cta_desc: "Contact our team to discuss your requirements, request samples or get a customized quote.",
    prod_cta_btn: "Contact Us Today",

    // ============================================================
    // PROJECTS PAGE
    // ============================================================
    proj_hero_tag: "Our Portfolio",
    proj_hero_title: "Projects",
    proj_hero_sub: "100+ successful projects delivered across trade, technology and investment sectors.",
    proj_feat_tag: "What We've Built",
    proj_feat_title: "Featured Projects",
    proj_feat_sub: "A selection of our most impactful projects across global markets.",
    proj1_cat: "Agricultural Export",
    proj1_title: "Sesame Export to China",
    proj1_loc: "Sudan → China",
    proj2_cat: "Logistics",
    proj2_title: "Port Sudan Logistics Hub",
    proj2_loc: "Port Sudan, Sudan",
    proj3_cat: "Technology",
    proj3_title: "ERP System Implementation",
    proj3_loc: "Riyadh, Saudi Arabia",
    proj4_cat: "Mining",
    proj4_title: "Gold Mining Partnership",
    proj4_loc: "Red Sea Hills, Sudan",
    proj5_cat: "Investment",
    proj5_title: "Riyadh Investment Tower",
    proj5_loc: "Riyadh, Saudi Arabia",
    proj6_cat: "Livestock",
    proj6_title: "Livestock Export to UAE",
    proj6_loc: "Sudan → UAE",
    proj7_cat: "Industrial",
    proj7_title: "Construction Materials Supply",
    proj7_loc: "Khartoum, Sudan",
    proj8_cat: "Technology",
    proj8_title: "Cloud Migration Project",
    proj8_loc: "Dubai, UAE",
    proj9_cat: "Natural Oils",
    proj9_title: "Sesame Oil Processing Plant",
    proj9_loc: "Gedaref, Sudan",
    proj_stat1: "Completed Projects",
    proj_stat2: "Countries Served",
    proj_stat3: "Happy Clients",
    proj_stat4: "Years Experience",

    // ============================================================
    // TECHNOLOGY PAGE
    // ============================================================
    tech_hero_tag: "Digital Transformation",
    tech_hero_title: "Technology Solutions",
    tech_hero_sub: "Innovative technology services driving digital transformation for modern enterprises.",
    tech_services_tag: "What We Deliver",
    tech_services_title: "Our Technology Services",
    tech_services_sub: "Comprehensive solutions tailored to your business needs.",
    tech_page_desc_erp: "Enterprise resource planning systems that integrate core business processes — finance, HR, supply chain, and operations — into a unified platform.",
    tech_page_desc_web: "Custom websites and web applications built with modern frameworks, optimized for performance, security and scalability.",
    tech_page_desc_mobile: "Native and cross-platform mobile applications for iOS and Android, delivering seamless user experiences.",
    tech_page_desc_ai: "AI-powered solutions including machine learning models, natural language processing and predictive analytics.",
    tech_page_desc_security: "Advanced security systems, threat detection, penetration testing and compliance solutions to protect your digital assets.",
    tech_page_desc_cloud: "Cloud migration, infrastructure setup, and managed services on AWS, Azure and Google Cloud platforms.",
    tech_process_tag: "How We Work",
    tech_process_title: "Our Development Process",
    tech_step1_title: "Discovery",
    tech_step1_desc: "We analyze your business needs, goals and requirements to craft a tailored strategy.",
    tech_step2_title: "Design",
    tech_step2_desc: "Our team creates intuitive designs and architecture that align with your brand identity.",
    tech_step3_title: "Development",
    tech_step3_desc: "We build robust, scalable solutions using modern technologies and best practices.",
    tech_step4_title: "Delivery",
    tech_step4_desc: "We deploy, test and provide ongoing support to ensure your solution runs flawlessly.",
    tech_cta_title: "Ready to Transform Your Business?",
    tech_cta_desc: "Let's discuss how our technology solutions can drive your digital transformation.",
    tech_cta_btn: "Start a Conversation",

    // ============================================================
    // INVESTMENT PAGE
    // ============================================================
    inv_hero_tag: "Grow With Us",
    inv_hero_title: "Investment Opportunities",
    inv_hero_sub: "Strategic partnerships and investment opportunities across high-growth sectors.",
    inv_intro_tag: "Why Invest With Us",
    inv_intro_title: "Building Wealth Through Strategic Partnerships",
    inv_intro_p1: "For over 30 years, Nashvell has created value for investors through carefully selected opportunities in trade, technology, infrastructure and natural resources. We combine deep market knowledge with a global network to deliver sustainable returns.",
    inv_feat1: "Diversified portfolio across sectors",
    inv_feat2: "Access to emerging African markets",
    inv_feat3: "Strong track record of returns",
    inv_feat4: "Expert risk management",
    inv_sectors_tag: "Our Focus Areas",
    inv_sectors_title: "Investment Sectors",
    inv_sec1_title: "Trade & Commerce",
    inv_sec1_desc: "Investment in export-import operations, supply chain infrastructure and cross-border trade facilitation.",
    inv_sec2_title: "Technology",
    inv_sec2_desc: "Venture investments in AI, cloud computing, cyber security and digital transformation startups.",
    inv_sec3_title: "Real Estate",
    inv_sec3_desc: "Premium commercial and residential property developments in Saudi Arabia and the wider region.",
    inv_sec4_title: "Logistics",
    inv_sec4_desc: "Investment in warehousing, port operations, fleet management and transportation networks.",
    inv_sec5_title: "Mining & Resources",
    inv_sec5_desc: "Strategic investments in gold, chromite and mineral extraction operations across Sudan.",
    inv_sec6_title: "Agriculture",
    inv_sec6_desc: "Investment in agricultural projects, processing facilities and sustainable farming initiatives.",
    inv_process_tag: "How It Works",
    inv_process_title: "Investment Process",
    inv_step1_title: "Consultation",
    inv_step1_desc: "We discuss your investment goals and risk appetite to identify suitable opportunities.",
    inv_step2_title: "Analysis",
    inv_step2_desc: "Our experts conduct thorough feasibility studies and due diligence on each opportunity.",
    inv_step3_title: "Partnership",
    inv_step3_desc: "We structure the investment and formalize the partnership with transparent terms.",
    inv_step4_title: "Growth",
    inv_step4_desc: "We actively manage investments and provide regular performance reports to partners.",
    inv_cta_title: "Ready to Invest?",
    inv_cta_desc: "Schedule a consultation with our investment team to explore opportunities.",
    inv_cta_btn: "Book a Consultation",

    // ============================================================
    // LOGISTICS PAGE
    // ============================================================
    log_hero_tag: "Global Supply Chain",
    log_hero_title: "Logistics Services",
    log_hero_sub: "End-to-end logistics solutions connecting Sudan to the world — by sea, air and land.",
    log_badge: "Global Network",
    log_intro_tag: "Our Services",
    log_intro_title: "Comprehensive Logistics Solutions",
    log_intro_desc: "From Port Sudan to global destinations, we manage every step of your supply chain with precision, reliability and care. Our integrated logistics platform ensures your cargo reaches its destination safely and on time.",
    log_feat1_title: "Sea Shipping",
    log_feat1_desc: "Full container and bulk shipping services through major global ports.",
    log_feat2_title: "Air Shipping",
    log_feat2_desc: "Express air freight for time-sensitive cargo to any destination worldwide.",
    log_feat3_title: "Custom Clearance",
    log_feat3_desc: "Expert customs documentation and clearance services at all major ports.",
    log_feat4_title: "Warehousing",
    log_feat4_desc: "Secure storage facilities with modern inventory management systems.",
    log_feat5_title: "Shipment Tracking",
    log_feat5_desc: "Real-time tracking and monitoring of your shipments from origin to destination.",
    log_stat1: "Countries Served",
    log_stat2: "Global Ports",
    log_stat3: "Shipments Delivered",
    log_stat4: "On-Time Delivery",
    log_track_tag: "Track Your Shipment",
    log_track_title: "Shipment Tracking",
    log_track_sub: "Enter your tracking number to get real-time updates on your shipment.",
    log_track_placeholder: "Enter tracking number (e.g. NSV-2024-001234)",
    log_track_btn: "Track Now",

    // ============================================================
    // MEDIA PAGE
    // ============================================================
    media_hero_tag: "News & Updates",
    media_hero_title: "Media Center",
    media_hero_sub: "Stay updated with the latest news, press releases and announcements.",
    media_news_tag: "Latest News",
    media_news_title: "Press & Media",
    media_news1_date: "March 15, 2024",
    media_news1_title: "Nashvell Expands Agricultural Exports to Asian Markets",
    media_news1_desc: "We are proud to announce the expansion of our agricultural export operations to include three new Asian markets, strengthening our global trade network.",
    media_news2_date: "February 28, 2024",
    media_news2_title: "New Technology Division Launches AI-Powered ERP Platform",
    media_news2_desc: "Our technology division has launched a new AI-powered ERP platform designed specifically for trading companies in the MENA region.",
    media_news3_date: "January 10, 2024",
    media_news3_title: "Port Sudan Logistics Hub Reaches Record Capacity",
    media_news3_desc: "Our logistics hub at Port Sudan has achieved record-breaking cargo throughput, cementing our position as a regional logistics leader.",
    media_news4_date: "December 5, 2023",
    media_news4_title: "Strategic Investment Partnership with Saudi Investors",
    media_news4_desc: "We have signed a strategic investment partnership with leading Saudi investors to develop commercial real estate projects in Riyadh.",
    media_news5_date: "November 18, 2023",
    media_news5_title: "New Mining Partnership Signed in Red Sea Hills",
    media_news5_desc: "A new mining partnership has been established to develop gold extraction operations in Sudan's mineral-rich Red Sea Hills region.",
    media_news6_date: "October 2, 2023",
    media_news6_title: "Nashvell Wins Best Exporter Award 2023",
    media_news6_desc: "We are honored to receive the Sudan Export Excellence Award for 2023, recognizing our contribution to the nation's export growth.",
    media_video_title: "Watch Our Story",
    media_video_desc: "Discover how Nashvell International Trading Co. Ltd. connects Sudan to the world through three decades of excellence.",
  },

  ar: {
    // ── Navbar ──
    nav_home: "الرئيسية",
    nav_about: "من نحن",
    nav_products: "منتجاتنا",
    nav_projects: "مشاريعنا",
    nav_investment: "الاستثمار",
    nav_technology: "التقنية",
    nav_logistics: "الخدمات اللوجستية",
    nav_media: "المركز الإعلامي",
    nav_gallery: "المعرض",
    nav_contact: "اتصل بنا",
    brand_tagline: "للتجارة الدولية المحدودة",
    lang_btn_text: "English",

    // ── Shared buttons ──
    btn_read_more: "اقرأ المزيد",
    btn_learn_more: "اعرف المزيد",

    // ── Hero Section (Home) ──
    hero_badge: "حلول متكاملة للشركات",
    hero_title: "رواد التجارة والاستثمارات المبتكرة",
    hero_subtitle: "شريكك الاستراتيجي للنجاح العالمي",
    hero_desc: "نقدم حلولاً متكاملة في التجارة الدولية، والخدمات اللوجستية، والاستثمارات الاستراتيجية، معتمدين على أحدث التقنيات لتحقيق النمو والتميز لشركائنا.",
    hero_btn_main: "اكتشف خدماتنا",
    hero_btn_outline: "تواصل معنا",
    hero_right_title: "تقنياتنا الأساسية",
    hero_right_sub: "نقود الابتكار في كل قطاع.",
    hero_right_btn: "استكشف التقنية",
    tech_icon_supply: "سلاسل الإمداد",
    tech_icon_data: "تحليل البيانات",
    tech_icon_automation: "الأتمتة",
    tech_icon_security: "الأمن السيبراني",
    tech_icon_cloud: "الخدمات السحابية",
    tech_icon_iot: "إنترنت الأشياء",
    stat_experience: "سنوات من الخبرة",
    stat_projects: "مشروع مكتمل",
    stat_clients: "عميل راضٍ",
    stat_countries: "دولة حول العالم",
    stat_products: "منتج سوداني",

    // ── Section Titles ──
    section_title_about: "عن ناشڤيل",
    section_subtitle_about: "إرث من الثقة ومستقبل من الابتكار.",
    section_title_products: "منتجاتنا",
    section_subtitle_products: "مجموعة متنوعة من المنتجات عالية الجودة التي تلبي المعايير العالمية.",
    section_title_services: "خدماتنا الأساسية",
    section_subtitle_services: "خدمات متكاملة مصممة لتحقيق الكفاءة والنمو.",
    section_title_tech_tag: "تقنياتنا",
    section_title_tech: "التقنية والابتكار",
    section_subtitle_tech_full: "حلول تقنية متكاملة مصممة لدفع التحول الرقمي للشركات في المنطقة.",
    section_subtitle_tech: "نسخر التكنولوجيا لإعادة تعريف معايير الصناعة.",
    section_title_investment: "فرص الاستثمار",
    section_subtitle_investment: "فرص استثمارية استراتيجية في قطاعات واعدة.",
    section_title_logistics: "خدمات لوجستية متقدمة",
    section_subtitle_logistics: "حلول لوجستية ذكية وفعالة لأعمالك.",
    section_title_partners: "شركاؤنا",
    section_subtitle_partners: "نفخر بالتعاون مع علامات تجارية عالمية رائدة.",
    section_title_certs: "الشهادات والاعتمادات",
    section_subtitle_certs: "ملتزمون بأعلى معايير الجودة والتميز.",
    section_title_gallery: "معرض الصور",
    section_subtitle_gallery: "لمحة عن عالم عملياتنا وإنجازاتنا.",
    section_title_video: "نبني المستقبل، معًا",
    section_subtitle_video: "شاهد رحلتنا واكتشف القيم التي تدفعنا إلى الأمام.",
    section_title_contact: "تواصل معنا",
    section_subtitle_contact: "نحن هنا للمساعدة. اتصل بنا لأي استفسار.",

    // ── Home: Products ──
    product_cat_export: "تصدير",
    product_title_agri: "منتجات زراعية",
    product_desc_agri: "سمسم، فول سوداني، كركديه والمزيد",
    product_cat_premium: "فاخر",
    product_title_oils: "زيوت طبيعية",
    product_desc_oils: "زيت السمسم، الصمغ العربي، زبدة الشيا",
    product_cat_live: "تصدير حي",
    product_title_livestock: "مواشي",
    product_desc_livestock: "أبقار، أغنام، جمال وماعز",
    product_cat_mining: "تعدين",
    product_title_mining: "التعدين والمعادن",
    product_desc_mining: "ذهب، كروميت، نحاس",
    product_cat_industrial: "صناعي",
    product_title_industrial: "منتجات صناعية",
    product_desc_industrial: "مواد بناء، معدات",
    product_btn_explore: "استكشف",

    // ── Home: Services ──
    service_title_logistics: "خدمات لوجستية",
    service_item_road: "شحن بري",
    service_item_air: "شحن جوي",
    service_item_customs: "تخليص جمركي",
    service_item_warehousing: "تخزين وتوزيع",
    service_item_tracking: "تتبع الشحنات",
    service_btn_learn: "اعرف المزيد",
    service_title_investment: "الاستثمار والمشاريع",
    service_item_opportunities: "فرص استثمارية",
    service_item_partnerships: "شراكات استراتيجية",
    service_item_feasibility: "دراسات جدوى",
    service_item_management: "إدارة المشاريع",
    service_title_global: "شراكات عالمية",
    service_desc_global: "نعمل مع شركاء حول العالم لبناء مستقبل أفضل وأكثر استدامة من خلال علاقات تجارية استراتيجية قوية.",

    // ── Home: Technology cards ──
    tech_btn_all: "عرض كل الخدمات",
    tech_card_title_erp: "أنظمة ERP",
    tech_card_desc_erp: "تخطيط موارد المؤسسات المصممة خصيصًا لاحتياجات عملك.",
    tech_card_title_web: "تطوير الويب",
    tech_card_desc_web: "مواقع وتطبيقات ويب حديثة ومتجاوبة.",
    tech_card_title_mobile: "تطبيقات الجوال",
    tech_card_desc_mobile: "تطبيقات iOS و Android لجماهير عالمية.",
    tech_card_title_ai: "الذكاء الاصطناعي",
    tech_card_desc_ai: "حلول مدعومة بالذكاء الاصطناعي للأتمتة والتحليلات.",
    tech_card_title_security: "الأمن السيبراني",
    tech_card_desc_security: "أنظمة أمان متقدمة لحماية أصولك الرقمية.",
    tech_card_title_cloud: "الحلول السحابية",
    tech_card_desc_cloud: "بنية تحتية سحابية قابلة للتطوير وخدمات ترحيل.",

    // ── Home: Preview panels ──
    preview_title_gallery: "معرض الصور",
    preview_title_video: "معرض الفيديو",
    preview_title_partners: "عملاؤنا وشركاؤنا",
    preview_title_certs: "شهاداتنا",
    preview_title_contact: "اتصل بنا",
    preview_btn_view_all: "عرض الكل",

    // ── Home: Values bar ──
    value_quality: "جودة عالية بمعايير عالمية",
    value_pricing: "أسعار تنافسية",
    value_delivery: "التسليم في الوقت المحدد",
    value_support: "دعم فني مستمر",
    value_innovation: "حلول مبتكرة",

    // ── Contact Form ──
    contact_label_name: "الاسم الكامل",
    contact_placeholder_name: "أدخل اسمك الكامل",
    contact_label_email: "البريد الإلكتروني",
    contact_placeholder_email: "أدخل بريدك الإلكتروني",
    contact_label_service: "الخدمة المطلوبة",
    contact_option_default: "اختر خدمة",
    contact_option_trade: "التجارة الدولية",
    contact_option_logistics: "الخدمات اللوجستية",
    contact_option_investment: "الاستثمار",
    contact_label_message: "الرسالة",
    contact_placeholder_message: "اكتب رسالتك هنا...",
    contact_btn_submit: "إرسال الرسالة",

    // ── Footer ──
    footer_desc: "شركة ناشڤيل للتجارة الدولية المحدودة هي شركة رائدة في تقديم الحلول الشاملة في مجالات التجارة والخدمات اللوجستية والاستثمار.",
    footer_title_links: "روابط سريعة",
    footer_title_newsletter: "النشرة البريدية",
    footer_newsletter_desc: "اشترك في نشرتنا البريدية للحصول على آخر التحديثات.",
    footer_placeholder_newsletter: "بريدك الإلكتروني",
    footer_btn_newsletter: "اشتراك",
    footer_design: "صُمم بدقة — التميز في كل التفاصيل",
    footer_copyright: "© 2024 ناشڤيل الدولية. جميع الحقوق محفوظة.",

    // ============================================================
    // ABOUT PAGE
    // ============================================================
    about_hero_tag: "تعرّف علينا",
    about_hero_title: "عن ناشڤيل",
    about_hero_subtitle: "ثلاثة عقود من التميز في التجارة الدولية والتقنية والاستثمار.",
    about_badge_num: "+30",
    about_badge_label: "سنة من التميز",
    about_intro_tag: "قصتنا",
    about_intro_title: "إرثٌ في التجارة الدولية",
    about_intro_p1: "تأسست شركة ناشڤيل للتجارة الدولية المحدودة عام 1994، ونمت من بيت تجاري إقليمي إلى مؤسسة دولية متنوعة الأنشطة. يقع مقرها الرئيسي في المملكة العربية السعودية بجذور عميقة في السودان، ونربط المنتجات الإفريقية بالأسواق العالمية.",
    about_intro_p2: "تشمل عملياتنا الصادرات الزراعية والزيوت الطبيعية والمواشي والتعدين والمنتجات الصناعية والحلول التقنية والخدمات اللوجستية والاستثمارات الاستراتيجية — مدفوعةً بالتزامنا بالجودة والنزاهة والشراكات طويلة الأمد.",
    about_feature1: "شبكة تجارة عالمية في أكثر من 25 دولة",
    about_feature2: "منتجات سودانية فاخرة تُصدَّر حول العالم",
    about_feature3: "حلول تقنية ولوجستية متكاملة",
    about_feature4: "أنظمة إدارة جودة معتمدة من ISO",
    about_btn_contact: "تواصل معنا",
    about_vission_tag: "ما يدفعنا",
    about_vission_title: "الرؤية والرسالة والقيم",
    about_vision_card_title: "رؤيتنا",
    about_vision_card_desc: "أن نكون الجسر الرائد الذي يربط المنتجات السودانية والموارد الإفريقية بالأسواق العالمية، ونضع معيار التميز في التجارة الدولية.",
    about_mission_card_title: "رسالتنا",
    about_mission_card_desc: "تقديم منتجات فاخرة وحلول تقنية مبتكرة وخدمات لوجستية موثوقة تخلق قيمة دائمة لعملائنا وشركائنا ومجتمعاتنا.",
    about_values_card_title: "قيمنا",
    about_values_card_desc: "النزاهة والجودة والابتكار والشراكة هي أسس كل ما نقوم به — وتوجّه علاقاتنا مع العملاء والموردين والمجتمعات.",
    about_team_tag: "قيادتنا",
    about_team_title: "تعرّف على الفريق",
    about_team_subtitle: "قادة ذوو خبرة يوجّهون رؤيتنا نحو التجارة العالمية والابتكار.",
    about_team_member1_name: "د. صلاح",
    about_team_member1_role: "مالك الشركة",
    about_team_member2_name: "خالد محمود",
    about_team_member2_role: "مدير العمليات",
    about_team_member3_name: "سارة إبراهيم",
    about_team_member3_role: "مديرة التقنية",
    about_team_member4_name: "عمر حسن",
    about_team_member4_role: "المدير المالي",
    about_certs_tag: "الجودة والثقة",
    about_certs_title: "شهاداتنا",
    about_cert1_title: "ISO 9001:2015",
    about_cert1_desc: "معتمد في نظام إدارة الجودة",
    about_cert2_title: "ISO 14001:2015",
    about_cert2_desc: "معتمد في الإدارة البيئية",
    about_cert3_title: "ISO 45001:2018",
    about_cert3_desc: "الصحة والسلامة المهنية",
    about_cert4_title: "أفضل مُصدِّر 2023",
    about_cert4_desc: "جائزة التميز في التصدير — السودان",

    // ============================================================
    // CONTACT PAGE
    // ============================================================
    contact_hero_tag: "تواصل معنا",
    contact_hero_title: "اتصل بنا",
    contact_hero_subtitle: "يسعدنا أن نسمع منك. تواصل معنا للشراكات أو الاستفسارات أو الدعم.",
    contact_info_tag: "معلومات التواصل",
    contact_info_title: "لنتحدث",
    contact_info_desc: "تواصل معنا عبر أي من القنوات التالية. فريقنا جاهز لمساعدتك.",
    contact_office_label: "المكتب الرئيسي",
    contact_office_ksa: "المملكة العربية السعودية",
    contact_phone_ksa_label: "الهاتف (السعودية)",
    contact_phone_ksa: "+966 50 441 5254",
    contact_phone_sd_label: "الهاتف (السودان)",
    contact_phone_sd: "+249 90 717 5005",
    contact_email_label: "البريد الإلكتروني",
    contact_email_main: "qqsalah@hotmail.com",
    contact_website_label: "الموقع الإلكتروني",
    contact_website_url: "www.nashvell.com",
    contact_form_tag: "أرسل رسالة",
    contact_form_title: "نموذج التواصل",
    contact_form_desc: "املأ النموذج أدناه وسيتواصل معك فريقنا خلال 24 ساعة.",
    contact_label_phone: "رقم الهاتف",
    contact_placeholder_phone: "+966 5X XXX XXXX",
    contact_label_subject: "الموضوع",
    contact_option_default_subject: "اختر موضوعًا",
    contact_option_inquiry: "استفسار عام",
    contact_option_tech: "خدمات التقنية",
    contact_option_media: "الإعلام والصحافة",
    contact_offices_tag: "مواقعنا",
    contact_offices_title: "مكاتبنا حول العالم",
    contact_office1_title: "الرياض، السعودية",
    contact_office1_desc: "المكتب الرئيسي\nحي الملك فهد، الرياض، السعودية\n+966 50 441 5254",
    contact_office2_title: "الخرطوم، السودان",
    contact_office2_desc: "المكتب الإقليمي\nالمقرن، الخرطوم، السودان\n+249 90 717 5005",
    contact_office3_title: "بورتسودان، السودان",
    contact_office3_desc: "المركز اللوجستي\nميناء بورتسودان، السودان\n+249 90 717 5005",

    // ============================================================
    // GALLERY PAGE
    // ============================================================
    gallery_hero_tag: "رحلة بصرية",
    gallery_hero_title: "معرضنا",
    gallery_hero_subtitle: "عرض بصري لمنتجاتنا ومشاريعنا وعملياتنا وفعالياتنا المؤسسية.",
    gallery_section_tag: "لحظات موثّقة",
    gallery_section_title: "معرض الصور",
    gallery_section_subtitle: "انقر على أي صورة لعرضها بالحجم الكامل.",

    // ============================================================
    // PRODUCTS PAGE
    // ============================================================
    prod_hero_tag: "ماذا نقدم",
    prod_hero_title: "منتجاتنا",
    prod_hero_sub: "منتجات سودانية فاخرة تُصدَّر إلى أكثر من 25 دولة حول العالم.",
    prod_catalog_tag: "كتالوجنا",
    prod_catalog_title: "استكشف منتجاتنا",
    prod_catalog_sub: "من أراضي السودان الخصبة إلى أسواق العالم — جودة تثق بها.",
    prod_filter_all: "كل المنتجات",
    prod_filter_agri: "زراعي",
    prod_filter_oils: "زيوت طبيعية",
    prod_filter_live: "مواشي",
    prod_filter_mine: "تعدين",
    prod_filter_indu: "صناعي",
    prod_cat_agri: "زراعي",
    prod_cat_oils: "زيوت طبيعية",
    prod_cat_live: "مواشي",
    prod_cat_mine: "تعدين",
    prod_cat_indu: "صناعي",
    prod_item1_title: "بذور السمسم",
    prod_item1_desc: "بذور سمسم بيضاء وذهبية فاخرة من مناطق السودان الخصبة، غنية بالزيت والنكهة.",
    prod_item2_title: "الكركديه",
    prod_item2_desc: "أزهار كركديه مجففة عالية الجودة، معروفة بلونها الزاهي وفوائدها الصحية، وتُصدَّر عالميًا.",
    prod_item3_title: "الفول السوداني",
    prod_item3_desc: "فول سوداني منتقى بعناية من قلب المناطق الزراعية السودانية، يلبّي معايير الجودة العالمية.",
    prod_item4_title: "زيت السمسم",
    prod_item4_desc: "زيت سمسم فاخر معصور على البارد، غني بالعناصر الغذائية ومثالي للاستخدامات الغذائية والتجميلية.",
    prod_item5_title: "الصمغ العربي",
    prod_item5_desc: "صمغ عربي من الدرجة الممتازة (هشاب وطلحة)، أجود صادرات السودان الطبيعية المستخدمة في الصناعات عالميًا.",
    prod_item6_title: "زبدة الشيا",
    prod_item6_desc: "زبدة شيا عضوية غير مكررة، مرغوبة في مستحضرات التجميل والعناية بالبشرة لخصائصها المغذية.",
    prod_item7_title: "تصدير الأبقار",
    prod_item7_desc: "أبقار سليمة وجيدة التغذية تُربّى في مراعي السودان الطبيعية، تلبّي معايير الحلال والتصدير.",
    prod_item8_title: "الأغنام والماعز",
    prod_item8_desc: "أغنام وماعز عالية الجودة للتصدير، تُربّى في ظروف مثالية مع شهادات بيطرية.",
    prod_item9_title: "الجمال",
    prod_item9_desc: "جمال فاخرة للتصدير إلى أسواق الخليج والأسواق الدولية، معروفة بقوتها وجودتها.",
    prod_item10_title: "الذهب",
    prod_item10_desc: "ذهب من مصادر أخلاقية من مناطق التعدين الغنية في السودان، مُكرَّر ومعتمد للتجارة الدولية.",
    prod_item11_title: "الكروميت",
    prod_item11_desc: "خام كروميت عالي الجودة للتطبيقات الصناعية، يلبّي المواصفات المعدنية الصارمة.",
    prod_item12_title: "خام النحاس",
    prod_item12_desc: "خام نحاس فاخر مستخرج من رواسب السودان الغنية بالمعادن، جاهز للمعالجة الصناعية.",
    prod_item13_title: "مواد البناء",
    prod_item13_desc: "أسمنت ومواد ركامية ومواد بناء عالية الجودة لمشاريع البنية التحتية الإقليمية.",
    prod_item14_title: "المعدات الصناعية",
    prod_item14_desc: "آلات ثقيلة ومعدات صناعية تُورَّد لقطاعات البناء والتصنيع.",
    prod_item15_title: "منتجات النسيج",
    prod_item15_desc: "منتجات قطنية ونسيجية مصنّعة وفق المعايير الدولية لأسواق الأزياء والصناعة العالمية.",
    prod_cta_title: "هل أنت مهتم بمنتجاتنا؟",
    prod_cta_desc: "تواصل مع فريقنا لمناقشة متطلباتك أو طلب عينات أو الحصول على عرض سعر مخصص.",
    prod_cta_btn: "تواصل معنا اليوم",

    // ============================================================
    // PROJECTS PAGE
    // ============================================================
    proj_hero_tag: "أعمالنا",
    proj_hero_title: "مشاريعنا",
    proj_hero_sub: "أكثر من 100 مشروع ناجح في قطاعات التجارة والتقنية والاستثمار.",
    proj_feat_tag: "ما أنجزناه",
    proj_feat_title: "مشاريع مميزة",
    proj_feat_sub: "مجموعة مختارة من أكثر مشاريعنا تأثيرًا في الأسواق العالمية.",
    proj1_cat: "تصدير زراعي",
    proj1_title: "تصدير السمسم إلى الصين",
    proj1_loc: "السودان ← الصين",
    proj2_cat: "الخدمات اللوجستية",
    proj2_title: "مركز بورتسودان اللوجستي",
    proj2_loc: "بورتسودان، السودان",
    proj3_cat: "التقنية",
    proj3_title: "تنفيذ نظام ERP",
    proj3_loc: "الرياض، السعودية",
    proj4_cat: "التعدين",
    proj4_title: "شراكة تعدين الذهب",
    proj4_loc: "جبال البحر الأحمر، السودان",
    proj5_cat: "الاستثمار",
    proj5_title: "برج الرياض الاستثماري",
    proj5_loc: "الرياض، السعودية",
    proj6_cat: "المواشي",
    proj6_title: "تصدير المواشي إلى الإمارات",
    proj6_loc: "السودان ← الإمارات",
    proj7_cat: "الصناعة",
    proj7_title: "توريد مواد البناء",
    proj7_loc: "الخرطوم، السودان",
    proj8_cat: "التقنية",
    proj8_title: "مشروع الترحيل السحابي",
    proj8_loc: "دبي، الإمارات",
    proj9_cat: "الزيوت الطبيعية",
    proj9_title: "مصنع معالجة زيت السمسم",
    proj9_loc: "القضارف، السودان",
    proj_stat1: "مشروع مكتمل",
    proj_stat2: "دولة مخدومة",
    proj_stat3: "عميل سعيد",
    proj_stat4: "سنة خبرة",

    // ============================================================
    // TECHNOLOGY PAGE
    // ============================================================
    tech_hero_tag: "التحول الرقمي",
    tech_hero_title: "الحلول التقنية",
    tech_hero_sub: "خدمات تقنية مبتكرة تقود التحول الرقمي للمؤسسات الحديثة.",
    tech_services_tag: "ما نقدمه",
    tech_services_title: "خدماتنا التقنية",
    tech_services_sub: "حلول شاملة مصممة خصيصًا لاحتياجات عملك.",
    tech_page_desc_erp: "أنظمة تخطيط موارد المؤسسات التي تدمج العمليات الأساسية — المالية والموارد البشرية وسلسلة الإمداد والعمليات — في منصة موحدة.",
    tech_page_desc_web: "مواقع وتطبيقات ويب مخصصة مبنية بأطر عمل حديثة، ومُحسّنة للأداء والأمان وقابلية التوسع.",
    tech_page_desc_mobile: "تطبيقات جوال أصلية ومتعددة المنصات لأنظمة iOS و Android، تقدم تجربة استخدام سلسة.",
    tech_page_desc_ai: "حلول مدعومة بالذكاء الاصطناعي تشمل نماذج تعلم الآلة ومعالجة اللغة الطبيعية والتحليلات التنبؤية.",
    tech_page_desc_security: "أنظمة أمان متقدمة وكشف التهديدات واختبار الاختراق وحلول الامتثال لحماية أصولك الرقمية.",
    tech_page_desc_cloud: "الترحيل السحابي وإعداد البنية التحتية والخدمات المُدارة على منصات AWS و Azure و Google Cloud.",
    tech_process_tag: "كيف نعمل",
    tech_process_title: "منهجية التطوير لدينا",
    tech_step1_title: "الاكتشاف",
    tech_step1_desc: "نحلل احتياجات عملك وأهدافه ومتطلباته لصياغة استراتيجية مخصصة.",
    tech_step2_title: "التصميم",
    tech_step2_desc: "يبتكر فريقنا تصاميم وبنية بديهية تتوافق مع هوية علامتك التجارية.",
    tech_step3_title: "التطوير",
    tech_step3_desc: "نبني حلولاً قوية وقابلة للتوسع باستخدام أحدث التقنيات وأفضل الممارسات.",
    tech_step4_title: "التسليم",
    tech_step4_desc: "ننشر ونختبر ونقدم دعمًا مستمرًا لضمان عمل حلّك بلا أخطاء.",
    tech_cta_title: "هل أنت مستعد لتحويل أعمالك؟",
    tech_cta_desc: "دعنا نناقش كيف يمكن لحلولنا التقنية أن تقود تحولك الرقمي.",
    tech_cta_btn: "ابدأ محادثة",

    // ============================================================
    // INVESTMENT PAGE
    // ============================================================
    inv_hero_tag: "انمُ معنا",
    inv_hero_title: "فرص الاستثمار",
    inv_hero_sub: "شراكات استراتيجية وفرص استثمارية في قطاعات عالية النمو.",
    inv_intro_tag: "لماذا تستثمر معنا",
    inv_intro_title: "بناء الثروة من خلال الشراكات الاستراتيجية",
    inv_intro_p1: "على مدى أكثر من 30 عامًا، خلقت ناشڤيل قيمة للمستثمرين من خلال فرص منتقاة بعناية في التجارة والتقنية والبنية التحتية والموارد الطبيعية. نجمع بين المعرفة العميقة بالسوق وشبكة عالمية لتحقيق عوائد مستدامة.",
    inv_feat1: "محفظة متنوعة عبر القطاعات",
    inv_feat2: "الوصول إلى الأسواق الإفريقية الناشئة",
    inv_feat3: "سجل حافل من العوائد",
    inv_feat4: "إدارة خبيرة للمخاطر",
    inv_sectors_tag: "مجالات تركيزنا",
    inv_sectors_title: "قطاعات الاستثمار",
    inv_sec1_title: "التجارة والتبادل التجاري",
    inv_sec1_desc: "الاستثمار في عمليات التصدير والاستيراد، والبنية التحتية لسلسلة الإمداد، وتيسير التجارة العابرة للحدود.",
    inv_sec2_title: "التقنية",
    inv_sec2_desc: "استثمارات في الشركات الناشئة في الذكاء الاصطناعي والحوسبة السحابية والأمن السيبراني والتحول الرقمي.",
    inv_sec3_title: "العقارات",
    inv_sec3_desc: "تطويرات عقارية تجارية وسكنية فاخرة في المملكة العربية السعودية والمنطقة الأوسع.",
    inv_sec4_title: "الخدمات اللوجستية",
    inv_sec4_desc: "الاستثمار في التخزين وعمليات الموانئ وإدارة الأساطيل وشبكات النقل.",
    inv_sec5_title: "التعدين والموارد",
    inv_sec5_desc: "استثمارات استراتيجية في عمليات استخراج الذهب والكروميت والمعادن في أنحاء السودان.",
    inv_sec6_title: "الزراعة",
    inv_sec6_desc: "الاستثمار في المشاريع الزراعية ومنشآت المعالجة ومبادرات الزراعة المستدامة.",
    inv_process_tag: "كيف تسير العملية",
    inv_process_title: "عملية الاستثمار",
    inv_step1_title: "الاستشارة",
    inv_step1_desc: "نناقش أهدافك الاستثمارية ومدى تقبّلك للمخاطر لتحديد الفرص المناسبة.",
    inv_step2_title: "التحليل",
    inv_step2_desc: "يجري خبراؤنا دراسات جدوى شاملة وفحصًا دقيقًا لكل فرصة.",
    inv_step3_title: "الشراكة",
    inv_step3_desc: "نهيكل الاستثمار ونرسّم الشراكة بشروط شفافة.",
    inv_step4_title: "النمو",
    inv_step4_desc: "ندير الاستثمارات بفاعلية ونقدم تقارير أداء دورية للشركاء.",
    inv_cta_title: "هل أنت مستعد للاستثمار؟",
    inv_cta_desc: "احجز استشارة مع فريق الاستثمار لدينا لاستكشاف الفرص.",
    inv_cta_btn: "احجز استشارة",

    // ============================================================
    // LOGISTICS PAGE
    // ============================================================
    log_hero_tag: "سلسلة الإمداد العالمية",
    log_hero_title: "الخدمات اللوجستية",
    log_hero_sub: "حلول لوجستية متكاملة تربط السودان بالعالم — برًا وبحرًا وجوًا.",
    log_badge: "شبكة عالمية",
    log_intro_tag: "خدماتنا",
    log_intro_title: "حلول لوجستية شاملة",
    log_intro_desc: "من بورتسودان إلى الوجهات العالمية، ندير كل خطوة في سلسلة إمدادك بدقة وموثوقية وعناية. تضمن منصتنا اللوجستية المتكاملة وصول شحنتك إلى وجهتها بأمان وفي الوقت المحدد.",
    log_feat1_title: "الشحن البحري",
    log_feat1_desc: "خدمات شحن الحاويات الكاملة والبضائع السائبة عبر الموانئ العالمية الرئيسية.",
    log_feat2_title: "الشحن الجوي",
    log_feat2_desc: "شحن جوي سريع للبضائع الحساسة للوقت إلى أي وجهة حول العالم.",
    log_feat3_title: "التخليص الجمركي",
    log_feat3_desc: "خدمات توثيق وتخليص جمركي احترافية في جميع الموانئ الرئيسية.",
    log_feat4_title: "التخزين",
    log_feat4_desc: "منشآت تخزين آمنة بأنظمة إدارة مخزون حديثة.",
    log_feat5_title: "تتبع الشحنات",
    log_feat5_desc: "تتبع ومراقبة شحناتك في الوقت الفعلي من المنشأ إلى الوجهة.",
    log_stat1: "دولة مخدومة",
    log_stat2: "ميناء عالمي",
    log_stat3: "شحنة تم تسليمها",
    log_stat4: "التسليم في الوقت المحدد",
    log_track_tag: "تتبّع شحنتك",
    log_track_title: "تتبع الشحنات",
    log_track_sub: "أدخل رقم التتبع للحصول على تحديثات فورية عن شحنتك.",
    log_track_placeholder: "أدخل رقم التتبع (مثال: NSV-2024-001234)",
    log_track_btn: "تتبّع الآن",

    // ============================================================
    // MEDIA PAGE
    // ============================================================
    media_hero_tag: "الأخبار والتحديثات",
    media_hero_title: "المركز الإعلامي",
    media_hero_sub: "ابقَ على اطلاع بآخر الأخبار والبيانات الصحفية والإعلانات.",
    media_news_tag: "آخر الأخبار",
    media_news_title: "الصحافة والإعلام",
    media_news1_date: "15 مارس 2024",
    media_news1_title: "ناشڤيل توسّع صادراتها الزراعية إلى الأسواق الآسيوية",
    media_news1_desc: "يسعدنا الإعلان عن توسيع عمليات التصدير الزراعي لدينا لتشمل ثلاثة أسواق آسيوية جديدة، مما يعزز شبكتنا التجارية العالمية.",
    media_news2_date: "28 فبراير 2024",
    media_news2_title: "قسم التقنية الجديد يطلق منصة ERP مدعومة بالذكاء الاصطناعي",
    media_news2_desc: "أطلق قسم التقنية لدينا منصة ERP جديدة مدعومة بالذكاء الاصطناعي مصممة خصيصًا للشركات التجارية في منطقة الشرق الأوسط وشمال إفريقيا.",
    media_news3_date: "10 يناير 2024",
    media_news3_title: "مركز بورتسودان اللوجستي يبلغ طاقة قياسية",
    media_news3_desc: "حقق مركزنا اللوجستي في بورتسودان إنتاجية شحن قياسية، مما رسّخ مكانتنا كرائد لوجستي إقليمي.",
    media_news4_date: "5 ديسمبر 2023",
    media_news4_title: "شراكة استثمارية استراتيجية مع مستثمرين سعوديين",
    media_news4_desc: "وقّعنا شراكة استثمارية استراتيجية مع مستثمرين سعوديين رائدين لتطوير مشاريع عقارية تجارية في الرياض.",
    media_news5_date: "18 نوفمبر 2023",
    media_news5_title: "توقيع شراكة تعدين جديدة في جبال البحر الأحمر",
    media_news5_desc: "تأسست شراكة تعدين جديدة لتطوير عمليات استخراج الذهب في منطقة جبال البحر الأحمر الغنية بالمعادن في السودان.",
    media_news6_date: "2 أكتوبر 2023",
    media_news6_title: "ناشڤيل تفوز بجائزة أفضل مُصدِّر 2023",
    media_news6_desc: "يشرّفنا الحصول على جائزة التميز في التصدير بالسودان لعام 2023، تقديرًا لإسهامنا في نمو صادرات البلاد.",
    media_video_title: "شاهد قصتنا",
    media_video_desc: "اكتشف كيف تربط شركة ناشڤيل للتجارة الدولية المحدودة السودان بالعالم عبر ثلاثة عقود من التميز.",
  }
};

function setLanguage(lang) {
  localStorage.setItem('language', lang);
  document.documentElement.lang = lang;
  document.documentElement.dir = lang === 'ar' ? 'rtl' : 'ltr';
  updateText(lang);
  updateLangButtons(lang);
}

function updateText(lang) {
  const dict = translations[lang] || translations.en;
  const elements = document.querySelectorAll('[data-i18n-key]');
  elements.forEach(el => {
    const key = el.getAttribute('data-i18n-key');
    const translation = dict[key];
    if (translation === undefined) return;
    if (el.tagName === 'INPUT' || el.tagName === 'TEXTAREA') {
      el.placeholder = translation;
    } else {
      el.innerText = translation;
    }
  });
}

function updateLangButtons(lang) {
  const arButton = document.getElementById('lang-ar-btn');
  const enButton = document.getElementById('lang-en-btn');
  if (arButton && enButton) {
    if (lang === 'ar') {
      arButton.style.display = 'none';
      enButton.style.display = 'inline-block';
    } else {
      arButton.style.display = 'inline-block';
      enButton.style.display = 'none';
    }
  }
}

document.addEventListener('DOMContentLoaded', () => {
  const langArBtn = document.getElementById('lang-ar-btn');
  const langEnBtn = document.getElementById('lang-en-btn');

  if (langArBtn) {
    langArBtn.addEventListener('click', (e) => {
      e.preventDefault();
      setLanguage('ar');
    });
  }
  if (langEnBtn) {
    langEnBtn.addEventListener('click', (e) => {
      e.preventDefault();
      setLanguage('en');
    });
  }

  const savedLang = localStorage.getItem('language') || 'en';
  setLanguage(savedLang);
});
